### ISSUE TITLE
 module "pages/charts/k/@antv/wx-f2.js" is not defined 

### ISSUE THREAD

**Issue by s3hengwu** [antvis/f2-canvas#3]
VM177:1 thirdScriptError 
 sdk uncaught third Error 
 module "pages/charts/k/@antv/wx-f2.js" is not defined 
 Error: module "pages/charts/k/@antv/wx-f2.js" is not defined
    at require (http://127.0.0.1:62212/appservice/__dev__/WAService.js:18:27142)
    at http://127.0.0.1:62212/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:62212/appservice/pages/charts/k/index.js:3:10
    at require (http://127.0.0.1:62212/appservice/__dev__/WAService.js:18:27248)
    at <anonymous>:129:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:62212/appservice/appservice?t=1545899896309:1757:23)

下载项目后，按步骤npm构建。运行报错

**Comment by jetaimeyu** [comment]
同上

**Comment by wangyang0210** [comment]
构建npm即可

**Comment by wangyang0210** [comment]
![image](https://user-images.githubusercontent.com/36377605/55734095-8c0ca300-5a51-11e9-83c2-738262c3bb04.png)

**Comment by zx870283980** [comment]
构建npm 还是报错
