### ISSUE TITLE
Cannot read property 'defaultView' of undefined;at SelectorQuery callback function

### ISSUE THREAD

**Issue by hanjiewx** [antvis/f2-canvas#6]
Cannot read property 'defaultView' of undefined;at SelectorQuery callback function
TypeError: Cannot read property 'defaultView' of undefined
    at Object.getStyle (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:1981:65)
    at Object.getWidth (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:1983:26)
    at t.e._initCanvas (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:2513:54)
    at new t (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:2498:100)
    at e.i._initCanvas (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:580:23)
    at e.i._init (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:587:18)
    at new e (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/wx-f2/index.js:465:19)
    at Object.initChart [as onInit] (http://127.0.0.1:16022/appservice/pages/column/column.js:14:11)
    at n.<anonymous> (http://127.0.0.1:16022/appservice/miniprogram_npm/@antv/f2-canvas/index.js:181:43)
    at Function.<anonymous> (http://127.0.0.1:16022/appservice/__dev__/WAService.js:1:481498)

**Comment by Leo-wxl** [comment]
怎么解决哈？

**Comment by qianqianjie1** [comment]
请问你怎么解决的啊

**Comment by qianqianjie1** [comment]
哦哦，我的是画布没有设置高度。。。
